# Generated by Django 3.2.25 on 2025-02-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('hr_email', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('hrstatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANDIDATE_ID', models.CharField(max_length=200)),
                ('resume_file', models.CharField(max_length=200)),
                ('par_skills', models.CharField(max_length=200)),
                ('exp_yr', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('uploaded_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jobdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('required_skills', models.CharField(max_length=200)),
                ('req_experiance', models.CharField(max_length=200)),
                ('req_education', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('HR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hr')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.CharField(max_length=200)),
                ('interview_sts', models.CharField(max_length=200)),
                ('CANDIDATE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidatereg')),
                ('JOB_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdescription')),
            ],
        ),
        migrations.AddField(
            model_name='hr',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
        migrations.AddField(
            model_name='candidatereg',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
    ]
