# Generated by Django 3.2.25 on 2025-02-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='job_desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
