# Generated by Django 3.2.25 on 2025-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_req_experiance_jobdescription_req_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOB_ID', models.CharField(max_length=200)),
                ('EMAIL', models.CharField(max_length=200)),
                ('FULL_NAME', models.CharField(max_length=200)),
                ('RESUME_ID', models.CharField(max_length=200)),
                ('review_status', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
