# Generated by Django 3.2.25 on 2025-03-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resumereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumereview',
            name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='resumereview',
            name='FULL_NAME',
        ),
        migrations.RemoveField(
            model_name='resumereview',
            name='JOB_ID',
        ),
        migrations.RemoveField(
            model_name='resumereview',
            name='RESUME_ID',
        ),
        migrations.AddField(
            model_name='resumereview',
            name='CANDIDATE_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.candidatereg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumereview',
            name='JOB_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.jobdescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumereview',
            name='RESUME',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='CANDIDATE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidatereg'),
        ),
    ]
