# Generated by Django 3.2.24 on 2025-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250305_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
