# Generated by Django 3.2.24 on 2025-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_interview_interview_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_summary',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
