# Generated by Django 3.2.24 on 2025-04-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resume_resume_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_summary',
            field=models.CharField(max_length=1000),
        ),
    ]
