# Generated by Django 4.2.5 on 2025-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_resume_resume_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
