# Generated by Django 5.2 on 2025-04-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobdescription_job_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applydate', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('CANDIDATE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidatereg')),
                ('JOB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdescription')),
            ],
        ),
    ]
