# Generated by Django 5.2 on 2025-04-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_apply_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='JOB_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.jobdescription'),
            preserve_default=False,
        ),
    ]
